services:
  app:
    build: .
    container_name: springboot-excel
    ports:
      - "8083:8083"
    restart: always
    volumes:
      - "D:/RENE/VERSIONAMIENTO_SISTEMAS/SISTEMA-SERVICIOS_PUSAK/data:/app/data"
    environment:
      - TZ=America/Guayaquil
      
volumes:
  postgres_data: