spring.application.name=becas
server.port=8083
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://10.181.1.113:5432/becas
spring.datasource.username=rsmunoz
spring.datasource.password=Senescyt2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# URL login sistema Servicios Pusak
app.logout.url=http://pusaktest.fomentoacademico.gob.ec:8080/ServiciosPusak/faces/login.xhtml

# URL base springboot
app.cargamasiva.base-url=http://10.181.1.136:8083

# Seguridad token
app.sso.secret=CLAVE_ULTRA_SEGURA_2026

# Guardar archivo Excel físico
spring.jackson.time-zone=America/Guayaquil
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guayaquil
app.upload.dir=/data/archivos_subidos_carga_masiva