spring.application.name=becas
server.port=8083
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://10.10.100.11:5432/becas
spring.datasource.username=pusak
spring.datasource.password=pfd24@4HF;$d
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# URL login sistema Servicios Pusak
app.logout.url=https://pusak.fomentoacademico.gob.ec/ServiciosPusak/faces/login.xhtml

# URL base springboot producción
app.cargamasiva.base-url=https://cargamasivapusak.fomentoacademico.gob.ec

# Seguridad token
app.sso.secret=CLAVE_ULTRA_SEGURA_2026

# Guardar archivo Excel físico
# Zona horaria
spring.jackson.time-zone=America/Guayaquil
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guayaquil
# Directorios
app.upload.dir=/data/archivos_subidos_carga_masiva
app.upload.dir.rechazo=/data/archivos_subidos_rechazo_masivo